### ISSUE TITLE
Caddyfile support?

### ISSUE THREAD

**Issue by IngwiePhoenix** [mholt/caddy-l4#90] opened 2022-12-20 03:48 UTC
Just a quick question :)

I am looking at proxying my TVHeadend to the outside, so I will have to set up a proxy to it's RTSP as well. The HTTP one I am working on.

But, I configure all things Caddy using the Caddyfile syntax (I find it much easier to maintain when in a shell editor like nano or vim).

Can I use the l4 apps in a Caddyfile too?

Thanks and kind regards,
Ingwie

**Comment by IndeedNotJames** [comment] 2022-12-20 05:13
Duplicate of #16

**Comment by mholt** [comment] 2022-12-20 05:33
Yeah, I hear ya. It's not a small undertaking though. Would require several days worth of effort I think.

**Closed** 2022-12-20 05:32 UTC
Labels: duplicate
