### ISSUE TITLE
Caddy-l4 proxy support UDP problems

### ISSUE THREAD

**Issue by lxhao61** [mholt/caddy-l4#24] opened 2021-06-16 21:01 UTC
This question comes from https://github.com/mholt/caddy-l4/issues/23
bug report：
root@VM-4-15-debian:~# journalctl -u caddy --no-pager
-- Logs begin at Thu 2021-06-17 04:32:40 CST, end at Thu 2021-06-17 04:46:38 CST. --
Jun 17 04:32:46 VM-4-15-debian systemd[1]: Starting Caddy...
Jun 17 04:32:47 VM-4-15-debian caddy[957]: {"level":"warn","ts":1623875567.0497217,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.HomeDir=.
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.AppDataDir=./caddy
Jun 17 04:32:47 VM-4-15-debian caddy[957]: {"level":"warn","ts":1623875567.372122,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.AppConfigDir=./caddy
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.ConfigAutosavePath=caddy/autosave.json
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.Version=v2.4.2 h1:chB106RlsIaY4mVEyq9OQM5g/9lHYVputo/LAX2ndFg=
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.GOOS=linux
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.GOARCH=amd64
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.Compiler=gc
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.NumCPU=1
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.GOMAXPROCS=1
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.Version=go1.16.5
Jun 17 04:32:47 VM-4-15-debian caddy[957]: os.Getwd=/
Jun 17 04:32:47 VM-4-15-debian caddy[957]: LANG=en_US.utf8
Jun 17 04:32:47 VM-4-15-debian caddy[957]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Jun 17 04:32:47 VM-4-15-debian caddy[957]: NOTIFY_SOCKET=/run/systemd/notify
Jun 17 04:32:47 VM-4-15-debian caddy[957]: LOGNAME=nobody
Jun 17 04:32:47 VM-4-15-debian caddy[957]: USER=nobody
Jun 17 04:32:47 VM-4-15-debian caddy[957]: INVOCATION_ID=56f8500c844c4f1c83185325bdb808c4
Jun 17 04:32:47 VM-4-15-debian caddy[957]: JOURNAL_STREAM=9:15996
Jun 17 04:32:47 VM-4-15-debian caddy[957]: {"level":"info","ts":1623875567.3747764,"msg":"using provided configuration","config_file":"/usr/local/etc/caddy/caddy.json","config_adapter":""}
Jun 17 04:32:47 VM-4-15-debian caddy[957]: {"level":"info","ts":1623875567.377124,"msg":"redirected default logger","from":"stderr","to":"/var/log/caddy/access.log"}
Jun 17 04:32:50 VM-4-15-debian systemd[1]: Started Caddy.
Jun 17 04:32:50 VM-4-15-debian caddy[957]: 2021/06/17 04:32:50 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Jun 17 04:32:50 VM-4-15-debian caddy[957]: 2021/06/17 04:32:50 [DEBUG] Fake-closing underlying packet conn

**Comment by francislavoie** [comment] 2021-06-16 21:03
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by mholt** [comment] 2021-06-16 21:10
> Jun 17 04:32:50 VM-4-15-debian caddy[957]: 2021/06/17 04:32:50 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

Did you run that command? Looks like a system misconfiguration, not a bug.

(Will reopen if it is a bug. Needs more info in the meantime.)

**Closed by mholt** 2021-06-16 21:10 UTC

**Comment by lxhao61** [comment] 2021-06-16 21:20
> > Jun 17 04:32:50 VM-4-15-debian caddy[957]: 2021/06/17 04:32:50 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
> 
> Did you run that command? Looks like a system misconfiguration, not a bug.
> 
> (Will reopen if it is a bug. Needs more info in the meantime.)

I have run this command. This is naiveproxy (forwardproxy) opening http/3 prompt, and it has nothing to do with proxy support UDP.

**Comment by mholt** [comment] 2021-06-16 21:33
So what's the problem?

Filling out the template Francis posted above will help us help you, otherwise we have other things keeping us busy.

**Comment by lxhao61** [comment] 2021-06-16 22:03
> Thanks for opening an issue! We'll look into this.
> 
> It's not immediately clear to us what is going on, so we'll need your help to understand it better.
> 
> Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.
> 
> I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. 
> 
> I've also included some helpful tips below the template. Feel free to let me know if you have any questions!
> 
> Thank you again for your report, we look forward to resolving it!
> 
> ## Template
> ```
> ## 1. Environment
> 
> ### 1a. Operating system and version
> 
> ```
> paste here
> ```
> 
> 
> ### 1b. Caddy version (run `caddy version` or paste commit SHA)
> 
> ```
> paste here
> ```
> 
> 
> ### 1c. Go version (if building Caddy from source; run `go version`)
> 
> ```
> paste here
> ```
> 
> 
> ## 2. Description
> 
> ### 2a. What happens (briefly explain what is wrong)
> 
> 
> 
> 
> ### 2b. Why it's a bug (if it's not obvious)
> 
> 
> 
> 
> ### 2c. Log output
> 
> ```
> paste terminal output or logs here
> ```
> 
> 
> 
> ### 2d. Workaround(s)
> 
> 
> 
> 
> ### 2e. Relevant links
> 
> 
> 
> 
> ## 3. Tutorial (minimal steps to reproduce the bug)
> ```
> 
> ## Helpful tips
> 1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.
> 2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
>    
>    * **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
>    * **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
>    * **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.
> 3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
>    
>    * Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
>    * Do not run Caddy inside containers.
>    * Run Caddy manually in your terminal; do not use systemd or other init systems.
>    * If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
>    * Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
>    * Note that ignoring this advice may result in delays, or even in your issue being closed. disappointed Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.
> 
> Example of a tutorial:
> 
> > Create a config file:
> > ```
> > { ... }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Open terminal and run Caddy:
> > ```
> > $ caddy ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make an HTTP request:
> > ```
> > $ curl ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Notice that the result is ___ but it should be ___.

## 1. Environment

### 1a. Operating system and version

```
Debian 10.2
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
caddy v2.4.2
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
go1.16.5
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)


Caddy-l4 proxy UDP is invalid


### 2b. Why it's a bug (if it's not obvious)

[DEBUG] Fake-closing underlying packet conn


### 2c. Log output

```
root@VM-4-15-debian:~# journalctl -u caddy --no-pager
-- Logs begin at Thu 2021-06-17 04:32:40 CST, end at Thu 2021-06-17 04:46:38 CST. --
Jun 17 04:32:46 VM-4-15-debian systemd[1]: Starting Caddy...
Jun 17 04:32:47 VM-4-15-debian caddy[957]: {"level":"warn","ts":1623875567.0497217,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.HomeDir=.
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.AppDataDir=./caddy
Jun 17 04:32:47 VM-4-15-debian caddy[957]: {"level":"warn","ts":1623875567.372122,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.AppConfigDir=./caddy
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.ConfigAutosavePath=caddy/autosave.json
Jun 17 04:32:47 VM-4-15-debian caddy[957]: caddy.Version=v2.4.2 h1:chB106RlsIaY4mVEyq9OQM5g/9lHYVputo/LAX2ndFg=
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.GOOS=linux
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.GOARCH=amd64
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.Compiler=gc
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.NumCPU=1
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.GOMAXPROCS=1
Jun 17 04:32:47 VM-4-15-debian caddy[957]: runtime.Version=go1.16.5
Jun 17 04:32:47 VM-4-15-debian caddy[957]: os.Getwd=/
Jun 17 04:32:47 VM-4-15-debian caddy[957]: LANG=en_US.utf8
Jun 17 04:32:47 VM-4-15-debian caddy[957]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Jun 17 04:32:47 VM-4-15-debian caddy[957]: NOTIFY_SOCKET=/run/systemd/notify
Jun 17 04:32:47 VM-4-15-debian caddy[957]: LOGNAME=nobody
Jun 17 04:32:47 VM-4-15-debian caddy[957]: USER=nobody
Jun 17 04:32:47 VM-4-15-debian caddy[957]: INVOCATION_ID=56f8500c844c4f1c83185325bdb808c4
Jun 17 04:32:47 VM-4-15-debian caddy[957]: JOURNAL_STREAM=9:15996
Jun 17 04:32:47 VM-4-15-debian caddy[957]: {"level":"info","ts":1623875567.3747764,"msg":"using provided configuration","config_file":"/usr/local/etc/caddy/caddy.json","config_adapter":""}
Jun 17 04:32:47 VM-4-15-debian caddy[957]: {"level":"info","ts":1623875567.377124,"msg":"redirected default logger","from":"stderr","to":"/var/log/caddy/access.log"}
Jun 17 04:32:50 VM-4-15-debian systemd[1]: Started Caddy.
Jun 17 04:32:50 VM-4-15-debian caddy[957]: 2021/06/17 04:32:50 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Jun 17 04:32:50 VM-4-15-debian caddy[957]: 2021/06/17 04:32:50 [DEBUG] Fake-closing underlying packet conn
```



### 2d. Workaround(s)




### 2e. Relevant links

https://github.com/mholt/caddy-l4/issues/23


## 3. Tutorial (minimal steps to reproduce the bug)

Example：
```
.......
    "layer4": {
      "servers": {
        "udp": {
          "listen": ["udp/0.0.0.0:443"],
          "routes": [{
            "handle": [{
              "handler": "proxy",
              "upstreams": [{
                "dial": ["127.0.0.1:7443"]
              }]
            }]
          }]
        }
      }
    },
.......
```

**Comment by mholt** [comment] 2021-06-16 22:16
Thanks, but there's not any new information there... :(

> Caddy-l4 proxy UDP is invalid

What does this mean?

> [DEBUG] Fake-closing underlying packet conn

This is not a bug. This is showing that we aren't leaking resources.

**Comment by lxhao61** [comment] 2021-06-16 22:27
> [DEBUG] Fake-closing underlying packet conn

You're welcome.
Proxy UDP is configured, but the proxy is unsuccessful.
As long as the above proxy UDP is configured, this "[DEBUG] Fake-closing underlying packet conn" will appear when the connection is made.
