### ISSUE TITLE
Caddyfile format support

### ISSUE THREAD

**Issue by Emeric-hub** [mholt/caddy-l4#148] opened 2023-09-12 19:03 UTC
Hi,

Thanks for this nice module.
I know that json is becoming a defacto standard, but i'm currently using folder configuration inclusion... lije a sites-enabled nginx functionality... and trying to do the same with "streams" content... (syslog / smtp /...)
And compiling /validating multiple json files is far more complicated than doing a folder include... so do you plan to support Caddyfile?

**Comment by francislavoie** [comment] 2023-09-12 19:04
Duplicate of https://github.com/mholt/caddy-l4/issues/16

**Closed by francislavoie** 2023-09-12 19:04 UTC
